config/routes.rb
Rails.application.routes.draw do

  resources :isolate do 
    get ":drug_id/reaction_detail" => "isolate#detail", as: "reaction_detail"
  end
  resources :clsi_breakpoint

  post 'upload_data_file' => 'data_file#upload'
  get 'upload_status' => 'data_file#upload_status'
  get 'isolate_drug_reactions' => 'welcome#download_isolate_drug_reactions', default: {format: 'xlsx'}

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @organisms = Organism.all
    @isolates_by_organism_code = Isolate.all.group_by(&:organism_code)
  end

  def download_isolate_drug_reactions
    @isolate_drug_reactions = IsolateDrugReaction.all
    respond_to do |format|
      format.xlsx
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_browse_organisms.html.slim
- if organisms.count > 0
  = link_to "Download Results", isolate_drug_reactions_path(format: :xlsx), class: "button success small"

  h2 Please choose an Isolate
  - organisms.each do |organism|
    h2
      small = organism.name

    - isolates = []
    - isolates_for_organism = isolates_by_organism_code[organism.code]
    - if isolates_for_organism
      - isolates_for_organism.each do |isolate|
        - isolates << link_to(isolate.id, isolate_url(isolate))
      p = isolates.join(", ").html_safe

app/views/welcome/index.html.slim
h1 CLSI Breakpoints


= simple_form_for :file_upload, url: upload_data_file_path, remote: true do |f|
  fieldset
    legend Upload Data File
    .left = f.input :upload, as: :file, label: false
    = f.submit "Upload",  class: "button small"
    p.status 
      b = "*Note: "
      |This will drop all records currently in the database, and import the new file.


.content-wrapper
  - if @organisms.count > 0 
    = render partial: 'browse_organisms', locals: {organisms: @organisms, isolates_by_organism_code: @isolates_by_organism_code}